/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef listmemberservice_CONSTANTS_H
#define listmemberservice_CONSTANTS_H

#include "listmemberservice_types.h"

namespace OpenStars { namespace Platform { namespace ListMemberService {

class listmemberserviceConstants {
 public:
  listmemberserviceConstants();

};

extern const listmemberserviceConstants g_listmemberservice_constants;

}}} // namespace

#endif
