/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "listmessageservice_constants.h"

namespace OpenStars { namespace Platform { namespace ListMessageService {

const listmessageserviceConstants g_listmessageservice_constants;

listmessageserviceConstants::listmessageserviceConstants() {
}

}}} // namespace

