/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef listmessageservice_CONSTANTS_H
#define listmessageservice_CONSTANTS_H

#include "listmessageservice_types.h"

namespace OpenStars { namespace Platform { namespace ListMessageService {

class listmessageserviceConstants {
 public:
  listmessageserviceConstants();

};

extern const listmessageserviceConstants g_listmessageservice_constants;

}}} // namespace

#endif
