/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TUserStoreService_H
#define TUserStoreService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "userstore_types.h"
#include "TDataService.h"

namespace OpenStars { namespace Platform { namespace UserStore {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TUserStoreServiceIf : virtual public TDataServiceIf {
 public:
  virtual ~TUserStoreServiceIf() {}
};

class TUserStoreServiceIfFactory : virtual public TDataServiceIfFactory {
 public:
  typedef TUserStoreServiceIf Handler;

  virtual ~TUserStoreServiceIfFactory() {}

  virtual TUserStoreServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TDataServiceIf* /* handler */) = 0;
};

class TUserStoreServiceIfSingletonFactory : virtual public TUserStoreServiceIfFactory {
 public:
  TUserStoreServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TUserStoreServiceIf>& iface) : iface_(iface) {}
  virtual ~TUserStoreServiceIfSingletonFactory() {}

  virtual TUserStoreServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TDataServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TUserStoreServiceIf> iface_;
};

class TUserStoreServiceNull : virtual public TUserStoreServiceIf , virtual public TDataServiceNull {
 public:
  virtual ~TUserStoreServiceNull() {}
};

class TUserStoreServiceClient : virtual public TUserStoreServiceIf, public TDataServiceClient {
 public:
  TUserStoreServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceClient(prot, prot) {}
  TUserStoreServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

class TUserStoreServiceProcessor : public TDataServiceProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TUserStoreServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TUserStoreServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
 public:
  TUserStoreServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TUserStoreServiceIf> iface) :
    TDataServiceProcessor(iface),
    iface_(iface) {
  }

  virtual ~TUserStoreServiceProcessor() {}
};

class TUserStoreServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TUserStoreServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TUserStoreServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TUserStoreServiceIfFactory > handlerFactory_;
};

class TUserStoreServiceMultiface : virtual public TUserStoreServiceIf, public TDataServiceMultiface {
 public:
  TUserStoreServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TUserStoreServiceIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<apache::thrift::stdcxx::shared_ptr<TUserStoreServiceIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
      TDataServiceMultiface::add(*iter);
    }
  }
  virtual ~TUserStoreServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TUserStoreServiceIf> > ifaces_;
  TUserStoreServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TUserStoreServiceIf> iface) {
    TDataServiceMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TUserStoreServiceConcurrentClient : virtual public TUserStoreServiceIf, public TDataServiceConcurrentClient {
 public:
  TUserStoreServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceConcurrentClient(prot, prot) {}
  TUserStoreServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceConcurrentClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}}} // namespace

#endif
