/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef contactstore_CONSTANTS_H
#define contactstore_CONSTANTS_H

#include "contactstore_types.h"

namespace OpenStars { namespace Platform { namespace ContactStore {

class contactstoreConstants {
 public:
  contactstoreConstants();

};

extern const contactstoreConstants g_contactstore_constants;

}}} // namespace

#endif
