/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef messagestore_CONSTANTS_H
#define messagestore_CONSTANTS_H

#include "messagestore_types.h"

namespace OpenStars { namespace Platform { namespace MessageStore {

class messagestoreConstants {
 public:
  messagestoreConstants();

};

extern const messagestoreConstants g_messagestore_constants;

}}} // namespace

#endif
